name: Build test package

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      #image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      #image: fedora:latest
      image: wachii/fedora-flatpak:base
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flatpak
        if: ${{false}}
        run: |
           #sudo apt-get -y install flatpak flatpak-builder
           #sudo flatpak --system remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
           #sudo dnf update -y
           sudo dnf install -y flatpak flatpak-builder python3-aiohttp python3-tenacity python3-gobject xorg-x11-server-Xvfb ccache zstd
           sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: test.flatpak
          manifest-path: 5.12/info.smplayer.SMPlayer.yml
          cache: true
          cache-key: smplayer-build-${{runner.os}}-5.12
