name: Build SMPlayer stable

on:
  workflow_dispatch:
  #release:
  #  types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged

    steps:
      - name: Get version
        run: |
            #git clone https://github.com/smplayer-dev/smplayer.git
            #cd smplayer
            #./get_version.sh
            #VERSION=`cat version`
            VERSION=21.8.0
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: smplayer-${{env.VERSION}}.flatpak
          manifest-path: smplayer-21.8/info.smplayer.SMPlayer.yml
          cache: true
          cache-key: smplayer-build-${{runner.os}}-stable
    
      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./smplayer-${{env.VERSION}}.flatpak
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
