name: Build flatpak package (5.12)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      #image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      image: wachii/flatpak-kde:5.12
      options: --privileged

    steps:
      - name: Get version
        run: |
            git clone https://github.com/smplayer-dev/smplayer.git
            cd smplayer
            ./get_version.sh
            VERSION=`cat version`
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: smplayer-${{env.VERSION}}-5.12.flatpak
          manifest-path: 5.12/info.smplayer.SMPlayer.yml
          cache: true
          cache-key: smplayer-build-${{runner.os}}

      - name: List
        run: flatpak list

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./5.12/smplayer-*.flatpak
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
