name: Build test package

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: bilelmoussaoui/flatpak-github-actions:kde-5.15
    #  options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flatpak
        run: |
           sudo apt-get -y install flatpak flatpak-builder
           sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: test.flatpak
          manifest-path: 5.12/info.smplayer.SMPlayer.yml
          cache: true
          cache-key: smplayer-build-${{runner.os}}-5.12
