name: Build SMPlayer 21.8

on:
  workflow_dispatch:
  #release:
  #  types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged

    steps:
      - name: Get version
        run: |
            VERSION=21.8.0
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: smplayer-${{env.VERSION}}.flatpak
          manifest-path: releases/21.8/info.smplayer.SMPlayer.yml
          cache: true
          cache-key: smplayer-build-${{runner.os}}-stable
